# Artificial Neural Network

### Importing the libraries

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
tf.__version__

'2.2.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [5]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:, :-1].values # Matrix of features, independent variables, input
y = dataset.iloc[:, -1].values # Dependent variable output 

In [6]:
print(X)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Part 2 - Building the ANN

### Initializing the ANN

In [9]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [11]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [12]:
ann.compile(optimizer='adam', loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [13]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 0s 505us/step - loss: 133034.7969
Epoch 2/100
240/240 [==============================] - 0s 497us/step - loss: 21713.6816
Epoch 3/100
240/240 [==============================] - 0s 551us/step - loss: 758.8817
Epoch 4/100
240/240 [==============================] - 0s 499us/step - loss: 470.9207
Epoch 5/100
240/240 [==============================] - 0s 694us/step - loss: 462.8455
Epoch 6/100
240/240 [==============================] - 0s 522us/step - loss: 453.5286
Epoch 7/100
240/240 [==============================] - 0s 513us/step - loss: 443.1769
Epoch 8/100
240/240 [==============================] - 0s 507us/step - loss: 431.0521
Epoch 9/100
240/240 [==============================] - 0s 507us/step - loss: 417.7651
Epoch 10/100
240/240 [==============================] - 0s 511us/step - loss: 403.2538
Epoch 11/100
240/240 [==============================] - 0s 520us/step - loss: 387.5104
Epoch 12/100
240/240 [=========================

240/240 [==============================] - 0s 505us/step - loss: 26.3705
Epoch 97/100
240/240 [==============================] - 0s 499us/step - loss: 26.0384
Epoch 98/100
240/240 [==============================] - 0s 499us/step - loss: 26.3710
Epoch 99/100
240/240 [==============================] - 0s 495us/step - loss: 26.3049
Epoch 100/100
240/240 [==============================] - 0s 499us/step - loss: 26.2575


### Predicting the results of the Test set

In [14]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)), 1))

[[430.31 431.23]
 [461.43 460.01]
 [464.96 461.14]
 ...
 [472.13 473.26]
 [439.09 438.  ]
 [458.23 463.28]]
